run:
  timeout: 3m

linters:
  presets:
    - bugs
    - unused
    - performance
    - error
    - format
  enable:
    - gosec
    - goimports

issues:
  exclude-use-default: false
  exclude-rules:
    - text: 'shadow: declaration of "(err|ctx)" shadows declaration at'
      linters: [ govet ]

linters-settings:
  govet:
    enable-all: true
  gosec:
    exclude-generated: true
    severity: "low"
    confidence: "low"
